<a href="https://colab.research.google.com/github/manan152003/dphi-colab/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

setting-up-of-tensorflow

In [ ]:
!pip install tensorflow 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf

reshaping 

In [ ]:
import torch 

In [ ]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype = torch.float32
)

In [ ]:
t1 = tf.constant([

           [[0, 1, 2, 3, 4],

            [5, 6, 7, 8, 9]],

           [[10, 11, 12, 13, 14],

            [15, 16, 17, 18, 19]],

           [[20, 21, 22, 23, 24],

            [25, 26, 27, 28, 29]],])
torch.tensor(t1.shape).prod()

tensor(30)

In [ ]:
t.shape

torch.Size([3, 3])

In [ ]:
t.type()

'torch.FloatTensor'

In [ ]:
t.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.tensor(t.shape).prod()

tensor(9)

In [ ]:
t.numel()

9

In [ ]:
print(t.reshape(1,9).squeeze())
print(t.reshape(1,9).squeeze().shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [ ]:
print(t.reshape(1,9).squeeze().unsqueeze(dim=0))
print(t.reshape(1,9).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [ ]:
def flatten(t):
  t = t.reshape(1,-1)
  t = t.squeeze()
  return t

In [ ]:
t = flatten(t)
t[::2]

tensor([1., 3., 5., 7., 9.])

In [ ]:
a = torch.tensor([
    [1,1,1,1,1,1],
    [2,2,2,2,2,2],
    [3,3,3,3,3,3]
], dtype = torch.int32)

In [ ]:
flatten(a)


tensor([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
       dtype=torch.int32)

concatenating tensors

In [ ]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype= torch.int8)

t2 = torch.tensor([
    [5,6],
    [7,8]
], dtype= torch.int16)

In [ ]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]], dtype=torch.int16)

**Linear Regression with Tensorflow Keras**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
boston_data = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Boston_Housing/Training_set_boston.csv")

In [ ]:
boston_data.head()

CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS   RAD    TAX  \
0  15.02340   0.0  18.10   0.0  0.6140  5.304  97.3  2.1007  24.0  666.0   
1   0.62739   0.0   8.14   0.0  0.5380  5.834  56.5  4.4986   4.0  307.0   
2   0.03466  35.0   6.06   0.0  0.4379  6.031  23.3  6.6407   1.0  304.0   
3   7.05042   0.0  18.10   0.0  0.6140  6.103  85.1  2.0218  24.0  666.0   
4   0.72580   0.0   8.14   0.0  0.5380  5.727  69.5  3.7965   4.0  307.0   

   PTRATIO       B  LSTAT  MEDV  
0     20.2  349.48  24.91  12.0  
1     21.0  395.62   8.47  19.9  
2     16.9  362.25   7.83  19.4  
3     20.2    2.52  23.29  13.4  
4     21.0  390.95  11.28  18.2

In [ ]:
X = boston_data.drop('MEDV', axis=1)
y = boston_data.MEDV

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
n_features = X.shape[1]
print(n_features)

13


In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from numpy.random import seed
import tensorflow


In [ ]:
# define the model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1))

In [ ]:


# import RMSprop optimizer
from tensorflow.keras.optimizers import RMSprop
optimizer = RMSprop(0.01)    # 0.01 is the learning rate



In [ ]:


model.compile(loss='mean_squared_error',optimizer=optimizer)    # compile the model



In [ ]:
seed_value = 42
seed(seed_value)        # If you build the model with given parameters, set_random_seed will help you produce the same result on multiple execution


# Recommended by Keras -------------------------------------------------------------------------------------
# 1. Set `PYTHONHASHSEED` environment variable at a fixed value
import os
os.environ['PYTHONHASHSEED']=str(seed_value)

# 2. Set `python` built-in pseudo-random generator at a fixed value
import random
random.seed(seed_value)

# 3. Set `numpy` pseudo-random generator at a fixed value
import numpy as np
np.random.seed(seed_value)
# Recommended by Keras -------------------------------------------------------------------------------------


# 4. Set the `tensorflow` pseudo-random generator at a fixed value
tensorflow.random.set_seed(seed_value) 
model.fit(X_train, y_train, epochs=10, batch_size=30, verbose = 1)    # fit the model

Epoch 1/10
11/11 [==============================] - 1s 2ms/step - loss: 244.1495
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 73.8451
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 75.9672
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 75.7670
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 65.8919
Epoch 6/10
11/11 [==============================] - 0s 2ms/step - loss: 73.1731
Epoch 7/10
11/11 [==============================] - 0s 2ms/step - loss: 63.1236
Epoch 8/10
11/11 [==============================] - 0s 2ms/step - loss: 72.2858
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 67.9203
Epoch 10/10
11/11 [==============================] - 0s 2ms/step - loss: 70.5173


In [ ]:
model.evaluate(X_test, y_test)

3/3 [==============================] - 0s 4ms/step - loss: 41.5930


41.5930290222168

In [ ]:


####################### Complete example to check the performance of the model with different learning rates #######################################
# define the model
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
model.add(Dense(8, activation='relu'))
model.add(Dense(1))

optimizer = RMSprop(0.1)    # 0.1 is the learning rate
model.compile(loss='mean_squared_error',optimizer=optimizer)    # compile the model

# fit the model 
model.fit(X_train, y_train, epochs=10, batch_size=30, verbose = 1)

# evaluate the model
print('The MSE value is: ', model.evaluate(X_test, y_test))



Epoch 1/10
11/11 [==============================] - 1s 2ms/step - loss: 35268.1758
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 559.4070
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 212.1510
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 139.3775
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 129.5609
Epoch 6/10
11/11 [==============================] - 0s 2ms/step - loss: 122.8495
Epoch 7/10
11/11 [==============================] - 0s 2ms/step - loss: 174.4107
Epoch 8/10
11/11 [==============================] - 0s 2ms/step - loss: 142.8209
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 201.2061
Epoch 10/10
3/3 [==============================] - 0s 4ms/step - loss: 122.8435
The MSE value is:  122.843505859375


EXERCISE 1

In [ ]:
# Play with learning rate
learning_rate = 0.01          # Replace ? with a floating-point number(decimal no.)
epochs = 10
optimizer = RMSprop(learning_rate)
model.compile(loss='mean_squared_error',optimizer=optimizer)    # Compile the model
model.fit(X_train, y_train, epochs=epochs, batch_size=30)       # Fit the model
model.evaluate(X_test, y_test)                                  # Evaluate the model

Epoch 1/10
11/11 [==============================] - 1s 2ms/step - loss: 106.8296
Epoch 2/10
11/11 [==============================] - 0s 2ms/step - loss: 73.6981
Epoch 3/10
11/11 [==============================] - 0s 2ms/step - loss: 74.2901
Epoch 4/10
11/11 [==============================] - 0s 2ms/step - loss: 72.2811
Epoch 5/10
11/11 [==============================] - 0s 2ms/step - loss: 67.1468
Epoch 6/10
11/11 [==============================] - 0s 2ms/step - loss: 69.1007
Epoch 7/10
11/11 [==============================] - 0s 2ms/step - loss: 68.2756
Epoch 8/10
11/11 [==============================] - 0s 2ms/step - loss: 65.4214
Epoch 9/10
11/11 [==============================] - 0s 2ms/step - loss: 68.6736
Epoch 10/10
3/3 [==============================] - 0s 4ms/step - loss: 46.4915


46.491546630859375

EXERCISE 2

In [ ]:
# Play with epochs
learning_rate = 0.01         
epochs = 50     # Replace ? with an integer
optimizer = RMSprop(learning_rate)
model.compile(loss='mean_squared_error',optimizer=optimizer)    # Compile the model
model.fit(X_train, y_train, epochs=epochs, batch_size=30)       # Fit the model
model.evaluate(X_test, y_test)                                  # Evaluate the model

Epoch 1/50
11/11 [==============================] - 1s 3ms/step - loss: 70.0362
Epoch 2/50
11/11 [==============================] - 0s 2ms/step - loss: 65.0259
Epoch 3/50
11/11 [==============================] - 0s 2ms/step - loss: 65.8137
Epoch 4/50
11/11 [==============================] - 0s 2ms/step - loss: 63.8883
Epoch 5/50
11/11 [==============================] - 0s 2ms/step - loss: 59.9468
Epoch 6/50
11/11 [==============================] - 0s 2ms/step - loss: 61.5756
Epoch 7/50
11/11 [==============================] - 0s 2ms/step - loss: 63.0611
Epoch 8/50
11/11 [==============================] - 0s 2ms/step - loss: 58.7888
Epoch 9/50
11/11 [==============================] - 0s 2ms/step - loss: 61.9014
Epoch 10/50
11/11 [==============================] - 0s 2ms/step - loss: 59.9055
Epoch 11/50
11/11 [==============================] - 0s 2ms/step - loss: 54.2819
Epoch 12/50
11/11 [==============================] - 0s 3ms/step - loss: 59.0154
Epoch 13/50
11/11 [==================

26.430286407470703

EXERCISE 3

In [ ]:
# play with learning rate and epochs
learning_rate = 0.009      # Replace ? with a floating-point number
epochs = 90         # Replace ? with an integer
optimizer = RMSprop(learning_rate)
model.compile(loss='mean_squared_error',optimizer=optimizer)    # Compile the model
model.fit(X_train, y_train, epochs=epochs, batch_size=30)       # Fit the model
model.evaluate(X_test, y_test)                                  # Evaluate the model

Epoch 1/90
11/11 [==============================] - 1s 2ms/step - loss: 43.7697
Epoch 2/90
11/11 [==============================] - 0s 2ms/step - loss: 33.8535
Epoch 3/90
11/11 [==============================] - 0s 2ms/step - loss: 35.2433
Epoch 4/90
11/11 [==============================] - 0s 2ms/step - loss: 33.0424
Epoch 5/90
11/11 [==============================] - 0s 2ms/step - loss: 28.7546
Epoch 6/90
11/11 [==============================] - 0s 2ms/step - loss: 33.4890
Epoch 7/90
11/11 [==============================] - 0s 2ms/step - loss: 27.1842
Epoch 8/90
11/11 [==============================] - 0s 2ms/step - loss: 28.2534
Epoch 9/90
11/11 [==============================] - 0s 2ms/step - loss: 31.4279
Epoch 10/90
11/11 [==============================] - 0s 2ms/step - loss: 26.5857
Epoch 11/90
11/11 [==============================] - 0s 2ms/step - loss: 32.3913
Epoch 12/90
11/11 [==============================] - 0s 2ms/step - loss: 36.4803
Epoch 13/90
11/11 [==================

29.031478881835938

EXERCISE 4

In [ ]:
# play with batch size
learning_rate = 0.01        
epochs = 150         
batch = 30      # Replace ? with an integer    
optimizer = RMSprop(learning_rate)
model.compile(loss='mean_squared_error',optimizer=optimizer)    # compile the model
model.fit(X_train, y_train, epochs=epochs, batch_size=batch)     # fit the model
model.evaluate(X_test, y_test)       # Evaluate the model

Epoch 1/150
11/11 [==============================] - 1s 2ms/step - loss: 47.9483
Epoch 2/150
11/11 [==============================] - 0s 2ms/step - loss: 27.7247
Epoch 3/150
11/11 [==============================] - 0s 3ms/step - loss: 31.9689
Epoch 4/150
11/11 [==============================] - 0s 3ms/step - loss: 30.0980
Epoch 5/150
11/11 [==============================] - 0s 3ms/step - loss: 27.8028
Epoch 6/150
11/11 [==============================] - 0s 3ms/step - loss: 30.1954
Epoch 7/150
11/11 [==============================] - 0s 2ms/step - loss: 26.6665
Epoch 8/150
11/11 [==============================] - 0s 2ms/step - loss: 26.7520
Epoch 9/150
11/11 [==============================] - 0s 2ms/step - loss: 29.6346
Epoch 10/150
11/11 [==============================] - 0s 2ms/step - loss: 24.9207
Epoch 11/150
11/11 [==============================] - 0s 2ms/step - loss: 31.7576
Epoch 12/150
11/11 [==============================] - 0s 2ms/step - loss: 34.0746
Epoch 13/150
11/11 [=====

**Making a Prediction (i.e 5th and Final step of Model Life-Cycle)**

In [ ]:
new_test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/Boston_Housing/Testing_set_boston.csv')
model.predict(new_test_data)

4/4 [==============================] - 0s 3ms/step


array([[25.828476 ],
       [36.68556  ],
       [14.915983 ],
       [23.1411   ],
       [15.093267 ],
       [17.282969 ],
       [14.915983 ],
       [14.915983 ],
       [19.645275 ],
       [17.41712  ],
       [17.132833 ],
       [14.915983 ],
       [14.915983 ],
       [16.649012 ],
       [18.364355 ],
       [20.170383 ],
       [14.915983 ],
       [14.915983 ],
       [38.23566  ],
       [14.915983 ],
       [24.921867 ],
       [26.025785 ],
       [14.915983 ],
       [21.02491  ],
       [14.915983 ],
       [14.915983 ],
       [20.310555 ],
       [14.915983 ],
       [15.696062 ],
       [17.053673 ],
       [18.750517 ],
       [23.784037 ],
       [20.378721 ],
       [21.644268 ],
       [14.915983 ],
       [14.915983 ],
       [30.414364 ],
       [20.331179 ],
       [16.913008 ],
       [20.368418 ],
       [14.915983 ],
       [29.095335 ],
       [39.39624  ],
       [15.211025 ],
       [23.331993 ],
       [15.6485615],
       [14.915983 ],
       [21.73

**Linear Regression and Hyperparameter Tuning using Tensorflow Keras and kerastuner**


Implementing hyperparameter tuning with Sklearn


In [ ]:
# ----------------------------- Functional Tuning - Option 1: using Sklearn  ------------------------------
# Goal: tune the batch size and epochs

# Import KerasRegressor class
from keras.wrappers.scikit_learn import KerasRegressor

# Define the model trhough a user-defined function
def create_model(optimizer=RMSprop(0.01)):
  model = Sequential()
  model.add(Dense(10, activation='relu', input_shape=(n_features,)))
  model.add(Dense(8, activation='relu'))
  model.add(Dense(1))
  model.compile(loss='mse', metrics=['mse'], optimizer=optimizer)    # compile the model
  return model
model = KerasRegressor(build_fn=create_model, verbose=1)

# Define the hyperparameters grid to be validated
batch_size = [10, 20, 30, 40, 60, 80, 100]
epochs = [10, 50, 100]
param_grid = dict(batch_size=batch_size, nb_epoch=epochs)
model = KerasRegressor(build_fn=create_model, verbose=1)
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, n_jobs=-1)

# Run the GridSearchCV process
grid_result = grid.fit(X_train, y_train, verbose = 1)

# Print the results of the best model
print('Best params: ' + str(grid_result.best_params_))

In [ ]:
# Import the cross validation evaluator
from sklearn.model_selection import cross_val_score

# Measure the model's performance
results = cross_val_score(grid.best_estimator_, X_test, y_test, cv=5)
print('Results: \n  * Mean:', -results.mean(), '\n  * Std:', results.std())


Implementing hyperparameter tuning with Keras

In [ ]:
# ----------------------------- Functional Tuning - Option 2: using Keras Tuner ------------------------------
# Goal: tune the learning rate

# 0. Install and import all the packages needed
!pip install -q -U keras-tuner
import kerastuner as kt

# 1. Define the general architecture of the model through a creation user-defined function
def model_builder(hp):
  model = Sequential()
  model.add(Dense(10, activation='relu', input_shape=(n_features,)))
  model.add(Dense(8, activation='relu'))
  model.add(Dense(1))
  hp_learning_rate = hp.Choice('learning_rate', values = [1e-1, 1e-2, 1e-3, 1e-4]) # Tuning the learning rate (four different values to test: 0.1, 0.01, 0.001, 0.0001)
  optimizer = RMSprop(learning_rate = hp_learning_rate)                            # Defining the optimizer
  model.compile(loss='mse',metrics=['mse'], optimizer=optimizer)                   # Compiling the model 
  return model                                                                     # Returning the defined model

# 2. Define the hyperparameters grid to be validated
tuner_rs = kt.RandomSearch(
              model_builder,                # Takes hyperparameters (hp) and returns a Model instance
              objective = 'mse',            # Name of model metric to minimize or maximize
              seed = 42,                    # Random seed for replication purposes
              max_trials = 5,               # Total number of trials (model configurations) to test at most. Note that the oracle may interrupt the search before max_trial models have been tested.
              directory='random_search')    # Path to the working directory (relative).

# 3. Run the GridSearchCV process
tuner_rs.search(X_train, y_train, epochs=10, validation_split=0.2, verbose=1)

In [ ]:
# 4.1. Print the summary results of the hyperparameter tuning procedure
tuner_rs.results_summary()

In [ ]:
# 4.2. Print the results of the best model
best_model = tuner_rs.get_best_models(num_models=1)[0]
best_model.evaluate(X_test, y_test)

In [ ]:
# 4.3. Print the best model's architecture
best_model.summary()

In [ ]:
# Load new test data
new_test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/Boston_Housing/Testing_set_boston.csv')
# make a prediction
best_model.predict(new_test_data)
